///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Ranorex_Jenkins_1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
          /// <summary>
          /// The class representing the Ranorex_Jenkins_1Repository element repository.
          /// </summary>
          [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
          [RepositoryFolder("ea2224a7-66fe-49ef-9998-56166d48aea9")]
          public partial class Ranorex_Jenkins_1Repository : RepoGenBaseFolder
          {
                    static Ranorex_Jenkins_1Repository instance = new Ranorex_Jenkins_1Repository();

                    /// <summary>
                    /// Gets the singleton class instance representing the Ranorex_Jenkins_1Repository element repository.
                    /// </summary>
                    [RepositoryFolder("ea2224a7-66fe-49ef-9998-56166d48aea9")]
                    public static Ranorex_Jenkins_1Repository Instance
                    {
                              get { return instance; }
                    }

                    /// <summary>
                    /// Repository class constructor.
                    /// </summary>
                    public Ranorex_Jenkins_1Repository() 
                              : base("Ranorex_Jenkins_1Repository", "/", null, 0, false, "ea2224a7-66fe-49ef-9998-56166d48aea9", ".\\RepositoryImages\\Ranorex_Jenkins_1Repositoryea2224a7.rximgres")
                    {
                    }

#region Variables

#endregion

                    /// <summary>
                    /// The Self item info.
                    /// </summary>
                    [RepositoryItemInfo("ea2224a7-66fe-49ef-9998-56166d48aea9")]
                    public virtual RepoItemInfo SelfInfo
                    {
                              get
                              {
                                        return _selfInfo;
                              }
                    }
          }

          /// <summary>
          /// Inner folder classes.
          /// </summary>
          [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
          public partial class Ranorex_Jenkins_1RepositoryFolders
          {
          }
#pragma warning restore 0436
}
